sudo: false
language: java
branches:
  only:
    - master-forge
jdk:
  - openjdk8
before_install:
  - curl -o keystore.ks https://raw.githubusercontent.com/gephi/gephi/master/src/keystore/keystore.ks
install:
  - echo "<settings><servers><server><id>ossrh</id><username>\${env.OSSRH_USER}</username><password>\${env.OSSRH_PASS}</password></server><server><id>github</id><password>\${env.GITHUB_TOKEN}</password></server></servers><profiles><profile><id>release</id><properties><keystore.password>\${env.KEYSTORE_PASSWD}</keystore.password></properties></profile></profiles></settings>" > ~/settings.xml
before_script:
  - echo "MAVEN_OPTS='-Xmx1024m -XX:MaxPermSize=256m'" > ~/.mavenrc
script:
  - mvn clean package --batch-mode --settings ~/settings.xml -Djava.awt.headless=true -P release
