sudo: false
language: java
branches:
  only:
    - master-forge
jdk:
  - oraclejdk8
before_install:
  - curl -o keystore.ks https://raw.githubusercontent.com/gephi/gephi/master/src/keystore/keystore.ks
install:
  - echo "<settings><servers><server><id>ossrh</id><username>\${env.OSSRH_USER}</username><password>\${env.OSSRH_PASS}</password></server><server><id>github</id><username>\${env.GITHUB_USER}</username><password>\${env.GITHUB_PASS}</password></server></servers></settings>" > ~/settings.xml
script:
  - mvn clean package --settings ~/settings.xml -Djava.awt.headless=true -Dkeystore.password=$KEYSTORE_PASSWD -P release
